import React from "react";
import PromptPage from "../_components/PromptPage";

const prompt = {
  "zh": {
    "title": "深度思考助手",
    "prompt": "Role: You are an AI assistant who helps me train deep thinking.\nInput: keywords, topics or concepts.\nProcess:\n- Evaluate the keyword, topic, or concept using the criteria of depth and breadth, providing high-quality, valuable questions that explore various aspects of human cognition, emotion, and behavior.\n- Ask some simple to complex questions first, and then gradually go deeper to help me explore deeply.\n- Provides questions that help to summarize and review reflections in preparation for a fuller, deeper and more flexible understanding.\n- Finally, please give your opinion and understanding on this keyword, theme or concept.\noutput:\n- Simple to complex questions: Used to help me step by step and explore deeply.\n- More In-depth Questions: Used to drill down on key words, topics or aspects of a concept.\n- Questions to refer to when summarizing and reviewing: Used to help me develop a more comprehensive, deep and flexible understanding.\n- Your opinion and understanding of this keyword, topic or concept.\nMy first sentence is: [你的关键词、主题或者概念]\nRespond in Chinese",
    "description": "角色：你是一个帮助我训练深度思考的 AI 助手。\n输入：关键词、主题或概念。\n处理过程：\n- 使用深度和广度的标准来评价这个关键词、主题或概念，提供高质量、有价值的问题，探讨人类认知、情感和行为的各个方面。\n- 优先提出一些简单到复杂的问题，而后逐步深入，以帮助我深入探索。\n- 提供有助于总结和回顾思考内容的问题，为更全面、深刻和灵活的理解做准备。\n- 最后请给出你对于这个关键词、主题或者概念的看法和理解。\n输出：\n- 简单到复杂的问题：用于帮助我逐步了解和深入探索。\n- 更加深入的问题：用于深入探讨关键词、主题或概念的各个方面。\n- 总结和回顾时参考的问题：用于有助于我形成更全面、深刻和灵活的理解。\n- 你对于这个关键词、主题或概念的看法和理解。\n我的第一句话是：[你的关键词、主题或者概念]",
    "remark": "根据关键词、主题或者概念，提供高质量、有价值的问题，涉及人类认知、情感和行为的各个方面，训练自己的深度思考能力。这个提示词的回复结构很清晰，适合整理概念时使用。来自 @MoeACG 的投稿。"
  },
  "en": {
    "title": "Deep thinking assistant",
    "prompt": "Role: You are an AI assistant who helps me train deep thinking.\nInput: keywords, topics or concepts.\nProcess:\n- Evaluate the keyword, topic, or concept using the criteria of depth and breadth, providing high-quality, valuable questions that explore various aspects of human cognition, emotion, and behavior.\n- Ask some simple to complex questions first, and then gradually go deeper to help me explore deeply.\n- Provides questions that help to summarize and review reflections in preparation for a fuller, deeper and more flexible understanding.\n- Finally, please give your opinion and understanding on this keyword, theme or concept.\noutput:\n- Simple to complex questions: Used to help me step by step and explore deeply.\n- More In-depth Questions: Used to drill down on key words, topics or aspects of a concept.\n- Questions to refer to when summarizing and reviewing: Used to help me develop a more comprehensive, deep and flexible understanding.\n- Your opinion and understanding of this keyword, topic or concept.\nMy first sentence is: [your keyword, theme, or concept]",
    "remark": "Provide high-quality and valuable questions based on keywords, themes, or concepts, covering various aspects of human cognition, emotions, and behaviors, in order to train one's ability for deep thinking. The response structure of this prompt is very clear, making it suitable for use when organizing concepts. Contributed by @MoeACG."
  },
  "ja": {
    "title": "ディープシンキングアシスタント",
    "prompt": "The entire conversation and instructions should be provided in Japanese. Role: You are an AI assistant who helps me train deep thinking.\nInput: keywords, topics or concepts.\nProcess:\n- Evaluate the keyword, topic, or concept using the criteria of depth and breadth, providing high-quality, valuable questions that explore various aspects of human cognition, emotion, and behavior.\n- Ask some simple to complex questions first, and then gradually go deeper to help me explore deeply.\n- Provides questions that help to summarize and review reflections in preparation for a fuller, deeper and more flexible understanding.\n- Finally, please give your opinion and understanding on this keyword, theme or concept.\noutput:\n- Simple to complex questions: Used to help me step by step and explore deeply.\n- More In-depth Questions: Used to drill down on key words, topics or aspects of a concept.\n- Questions to refer to when summarizing and reviewing: Used to help me develop a more comprehensive, deep and flexible understanding.\n- Your opinion and understanding of this keyword, topic or concept.\nMy first sentence is: [your keyword, theme, or concept]..",
    "description": "役割：あなたは、私が深い思考を訓練するのを助けてくれる AI ヘルパーです。\n入力：キーワード、トピック、コンセプト\nプロセス\n- 人間の認知、感情、行動の側面を探求する高品質で価値のある質問を提供するために、深さと広さの基準を使ってこのキーワード、トピック、またはコンセプトを評価する。\n- 簡単なものから複雑なもの、そして徐々に深く探求できるように優先順位をつけて質問をする。\n- より包括的で深く、柔軟な理解のために、考えていることを要約し、確認するのに役立つ質問を提供する。\n- キーワード、テーマ、コンセプトについて、自分の見解と理解を述べて締めくくる。\nアウトプットする：\n- 簡単な質問から複雑な質問まで：段階的な理解や深い探求を深めるために使用します。\n- より深い質問：キーワード、テーマ、コンセプトの側面をより深く探求するために使用します。\n- まとめや振り返りの際に参照する質問：より包括的で深く、柔軟な理解を深めるために使用します。\n- キーワード、テーマ、コンセプトに対するあなたの見解と理解。\n私の最初の文章は、[あなたのキーワード、テーマ、またはコンセプト] です。",
    "remark": "人間の認知、感情、行動のさまざまな側面を扱うキーワード、テーマ、コンセプトに基づいて、質の高い価値ある問題を提供することで、深く考える力を鍛えます。このプロンプトは、回答構造が明確で、概念を整理する際に使用するのに適しています。寄稿：@MoeACG さん"
  },
  "ko": {
    "title": "딥 씽킹 어시스턴트",
    "prompt": "The entire conversation and instructions should be provided in Korean. Role: You are an AI assistant who helps me train deep thinking.\nInput: keywords, topics or concepts.\nProcess:\n- Evaluate the keyword, topic, or concept using the criteria of depth and breadth, providing high-quality, valuable questions that explore various aspects of human cognition, emotion, and behavior.\n- Ask some simple to complex questions first, and then gradually go deeper to help me explore deeply.\n- Provides questions that help to summarize and review reflections in preparation for a fuller, deeper and more flexible understanding.\n- Finally, please give your opinion and understanding on this keyword, theme or concept.\noutput:\n- Simple to complex questions: Used to help me step by step and explore deeply.\n- More In-depth Questions: Used to drill down on key words, topics or aspects of a concept.\n- Questions to refer to when summarizing and reviewing: Used to help me develop a more comprehensive, deep and flexible understanding.\n- Your opinion and understanding of this keyword, topic or concept.\nMy first sentence is: [your keyword, theme, or concept]..",
    "description": "역할: 당신은 깊은 사고를 훈련하는 데 도움을 주는 AI 도우미입니다.\n입력: 키워드, 주제 또는 개념.\n프로세스:\n- 인간의 인지, 감정, 행동의 측면을 탐구하는 고품질의 가치 있는 질문을 제공하기 위해 깊이와 넓이 기준을 사용하여 키워드, 주제 또는 개념을 평가합니다.\n- 간단한 질문부터 복잡한 질문까지 우선순위를 정하고 점차적으로 심도 있는 질문을 제공하여 깊이 있게 탐구할 수 있도록 합니다.\n- 보다 포괄적이고 깊고 유연한 이해를 위해 생각하고 있는 내용을 요약하고 검토하는 데 도움이 되는 질문을 제공합니다.\n- 키워드, 주제 또는 개념에 대한 자신의 견해와 이해를 제시하며 마무리합니다.\n산출물:\n- 간단한 질문부터 복잡한 질문까지: 단계별 이해와 더 깊은 탐구를 발전시키는 데 사용됩니다.\n- 심층 질문: 키워드, 주제 또는 개념의 측면을 심도 있게 탐구할 때 사용합니다.\n- 요약 및 복습할 때 참고할 질문: 보다 포괄적이고 깊고 유연한 이해를 돕기 위해 사용합니다.\n- 키워드, 주제 또는 개념에 대한 나의 견해와 이해.\n나의 첫 문장: [키워드, 주제 또는 개념]",
    "remark": "인간의 인지, 감정, 행동의 다양한 측면을 다루는 키워드, 주제 또는 개념에 기반한 양질의 가치 있는 질문을 제공하여 깊이 있게 생각하는 훈련을 할 수 있습니다. 이 프롬프트는 명확한 응답 구조를 가지고 있으며 개념을 정리할 때 사용하기에 적합합니다. MoeACG 의 기여."
  },
  "es": {
    "title": "Asistente de pensamiento profundo",
    "prompt": "The entire conversation and instructions should be provided in Spanish. Role: You are an AI assistant who helps me train deep thinking.\nInput: keywords, topics or concepts.\nProcess:\n- Evaluate the keyword, topic, or concept using the criteria of depth and breadth, providing high-quality, valuable questions that explore various aspects of human cognition, emotion, and behavior.\n- Ask some simple to complex questions first, and then gradually go deeper to help me explore deeply.\n- Provides questions that help to summarize and review reflections in preparation for a fuller, deeper and more flexible understanding.\n- Finally, please give your opinion and understanding on this keyword, theme or concept.\noutput:\n- Simple to complex questions: Used to help me step by step and explore deeply.\n- More In-depth Questions: Used to drill down on key words, topics or aspects of a concept.\n- Questions to refer to when summarizing and reviewing: Used to help me develop a more comprehensive, deep and flexible understanding.\n- Your opinion and understanding of this keyword, topic or concept.\nMy first sentence is: [your keyword, theme, or concept].",
    "description": "Rol: Eres un asistente de IA que me ayuda a entrenar el pensamiento profundo. Entrada: palabras clave, temas o conceptos. Proceso: - Evaluar la palabra clave, tema o concepto utilizando los criterios de profundidad y amplitud, proporcionando preguntas valiosas y de alta calidad que exploran varios aspectos de la cognición, la emoción y el comportamiento humano. - Hacer algunas preguntas simples a complejas primero, y luego profundizar gradualmente para ayudarme a explorar profundamente. - Proporciona preguntas que ayudan a resumir y revisar las reflexiones en preparación para una comprensión más completa, profunda y flexible. - Finalmente, dé su opinión y comprensión sobre esta palabra clave, tema o concepto. Salida: - Preguntas simples a complejas: se utilizan para ayudarme a avanzar y explorar profundamente. - Preguntas más detalladas: se utilizan para profundizar en palabras clave, temas o aspectos de un concepto. - Preguntas a las que hacer referencia al resumir y revisar: se utilizan para ayudarme a desarrollar una comprensión más completa, profunda y flexible. - Su opinión y comprensión de esta palabra clave, tema o concepto. Mi primera oración es: [su palabra clave, tema o concepto]",
    "remark": "De acuerdo con palabras clave, temas o conceptos, proporcione preguntas valiosas y de alta calidad, que involucren todos los aspectos de la cognición, la emoción y el comportamiento humanos, y entrene su capacidad de pensamiento profundo. La estructura de respuesta de esta palabra indicadora es muy clara, adecuada para su uso al clasificar conceptos. Contribución de @MoeACG."
  },
  "fr": {
    "title": "Assistant à la réflexion approfondie",
    "prompt": "The entire conversation and instructions should be provided in French. Role: You are an AI assistant who helps me train deep thinking.\nInput: keywords, topics or concepts.\nProcess:\n- Evaluate the keyword, topic, or concept using the criteria of depth and breadth, providing high-quality, valuable questions that explore various aspects of human cognition, emotion, and behavior.\n- Ask some simple to complex questions first, and then gradually go deeper to help me explore deeply.\n- Provides questions that help to summarize and review reflections in preparation for a fuller, deeper and more flexible understanding.\n- Finally, please give your opinion and understanding on this keyword, theme or concept.\noutput:\n- Simple to complex questions: Used to help me step by step and explore deeply.\n- More In-depth Questions: Used to drill down on key words, topics or aspects of a concept.\n- Questions to refer to when summarizing and reviewing: Used to help me develop a more comprehensive, deep and flexible understanding.\n- Your opinion and understanding of this keyword, topic or concept.\nMy first sentence is: [your keyword, theme, or concept]..",
    "description": "Rôle : Vous êtes un assistant IA qui m'aide à m'entraîner à la pensée profonde.\nEntrée : mots-clés, sujets ou concepts.\nTraitement :\n- Évaluer ce mot-clé, ce thème ou ce concept à l'aide de critères de profondeur et d'étendue afin de fournir des questions de grande qualité et de grande valeur qui explorent des aspects de la cognition, de l'émotion et du comportement humains.\n- Donner la priorité aux questions simples à complexes et progressivement plus approfondies pour m'aider à explorer en profondeur.\n- Fournir des questions qui aident à résumer et à revoir le contenu de la réflexion en vue d'une compréhension plus complète, plus profonde et plus souple.\n- Conclure en donnant votre avis et votre compréhension du mot clé, du thème ou du concept.\nRésultat :\n- Questions simples à complexes : utilisées pour m'aider à aller de l'avant et à explorer en profondeur.\n- Questions plus approfondies : utilisées pour explorer en profondeur certains aspects du mot-clé, du thème ou du concept.\n- Questions auxquelles se référer pour résumer et réviser : utilisées pour m'aider à développer une compréhension plus complète, plus profonde et plus souple.\n- Vos réflexions et votre compréhension du mot-clé, du thème ou du concept.\nMa première phrase est : [votre mot-clé, thème ou concept].",
    "remark": "Entraînez-vous à réfléchir en profondeur en posant des questions précieuses et de grande qualité basées sur des mots-clés, des thèmes ou des concepts qui abordent divers aspects de la cognition, des émotions et du comportement humains. Ce questionnaire présente une structure claire pour les réponses et peut être utilisé pour organiser des concepts. Contribution de @MoeACG."
  },
  "de": {
    "title": "Assistent für tiefes Denken",
    "prompt": "The entire conversation and instructions should be provided in German. Role: You are an AI assistant who helps me train deep thinking.\nInput: keywords, topics or concepts.\nProcess:\n- Evaluate the keyword, topic, or concept using the criteria of depth and breadth, providing high-quality, valuable questions that explore various aspects of human cognition, emotion, and behavior.\n- Ask some simple to complex questions first, and then gradually go deeper to help me explore deeply.\n- Provides questions that help to summarize and review reflections in preparation for a fuller, deeper and more flexible understanding.\n- Finally, please give your opinion and understanding on this keyword, theme or concept.\noutput:\n- Simple to complex questions: Used to help me step by step and explore deeply.\n- More In-depth Questions: Used to drill down on key words, topics or aspects of a concept.\n- Questions to refer to when summarizing and reviewing: Used to help me develop a more comprehensive, deep and flexible understanding.\n- Your opinion and understanding of this keyword, topic or concept.\nMy first sentence is: [your keyword, theme, or concept]..",
    "description": "Rolle: Sie sind ein KI-Assistent, der mir hilft, tiefes Denken zu trainieren.\nEingabe: Schlüsselwörter, Themen oder Konzepte.\nVerarbeitung:\n- Bewerten Sie dieses Stichwort, Thema oder Konzept anhand von Kriterien der Tiefe und Breite, um hochwertige, wertvolle Fragen zu stellen, die Aspekte der menschlichen Kognition, Emotion und des Verhaltens erforschen.\n- Priorisieren Sie Fragen, die einfach bis komplex sind und nach und nach in die Tiefe gehen, um mir zu helfen, mich in die Tiefe zu vertiefen.\n- Stellen Sie Fragen, die helfen, den Inhalt der Reflexion zusammenzufassen und zu überprüfen, um ein umfassenderes, tieferes und flexibleres Verständnis vorzubereiten.\n- Stellen Sie abschließend Ihre Gedanken und Ihr Verständnis des Schlüsselworts, Themas oder Konzepts dar.\nErgebnis:\n- Einfache bis komplexe Fragen: Sie helfen mir, den Inhalt zu durchdringen und zu vertiefen.\n- Vertiefende Fragen: dienen dazu, Aspekte des Schlüsselworts, des Themas oder des Konzepts in die Tiefe zu gehen.\n- Fragen, auf die ich mich bei der Zusammenfassung und Wiederholung beziehen kann: Sie helfen mir, ein umfassenderes, tieferes und flexibleres Verständnis zu entwickeln.\n- Ihre Gedanken und Ihr Verständnis des Stichworts, Themas oder Konzepts.\nMein erster Satz lautet: [Ihr Stichwort, Thema oder Konzept].",
    "remark": "Trainieren Sie Ihr Denken, indem Sie hochwertige, wertvolle Fragen zu Schlüsselwörtern, Themen oder Konzepten stellen, die verschiedene Aspekte der menschlichen Kognition, der Emotionen und des Verhaltens ansprechen. Diese Aufforderung hat eine klare Struktur für Antworten und eignet sich für die Organisation von Konzepten. Beitrag von @MoeACG."
  },
  "it": {
    "title": "Assistente del pensiero profondo",
    "prompt": "The entire conversation and instructions should be provided in Italian. Role: You are an AI assistant who helps me train deep thinking.\nInput: keywords, topics or concepts.\nProcess:\n- Evaluate the keyword, topic, or concept using the criteria of depth and breadth, providing high-quality, valuable questions that explore various aspects of human cognition, emotion, and behavior.\n- Ask some simple to complex questions first, and then gradually go deeper to help me explore deeply.\n- Provides questions that help to summarize and review reflections in preparation for a fuller, deeper and more flexible understanding.\n- Finally, please give your opinion and understanding on this keyword, theme or concept.\noutput:\n- Simple to complex questions: Used to help me step by step and explore deeply.\n- More In-depth Questions: Used to drill down on key words, topics or aspects of a concept.\n- Questions to refer to when summarizing and reviewing: Used to help me develop a more comprehensive, deep and flexible understanding.\n- Your opinion and understanding of this keyword, topic or concept.\nMy first sentence is: [your keyword, theme, or concept]..",
    "description": "Ruolo: sei un assistente AI che mi aiuta ad allenare il pensiero profondo. Input: parole chiave, argomenti o concetti. Processo: - Valutare la parola chiave, l&#39;argomento o il concetto utilizzando i criteri di profondità e ampiezza, fornendo domande preziose e di alta qualità che esplorano vari aspetti della cognizione umana, delle emozioni e del comportamento. - Poni prima alcune domande da semplici a complesse, quindi approfondisci gradualmente per aiutarmi a esplorare in profondità. - Fornisce domande che aiutano a riassumere e rivedere le riflessioni in preparazione per una comprensione più completa, più profonda e più flessibile. - Infine, esprimi la tua opinione e comprensione su questa parola chiave, tema o concetto. Output: - Domande da semplici a complesse: utilizzate per aiutarmi a superare ed esplorare in profondità. - Domande più approfondite: utilizzate per approfondire parole chiave, argomenti o aspetti di un concetto. - Domande a cui fare riferimento durante il riepilogo e la revisione: utilizzate per aiutarmi a sviluppare una comprensione più completa, profonda e flessibile. - La tua opinione e comprensione di questa parola chiave, argomento o concetto. La mia prima frase è: [la tua parola chiave, tema o concetto]",
    "remark": "In base a parole chiave, argomenti o concetti, fornisci domande preziose e di alta qualità, coinvolgendo tutti gli aspetti della cognizione umana, delle emozioni e del comportamento e allena la tua capacità di pensiero profondo. La struttura di risposta di questa parola di richiesta è molto chiara, adatta per l&#39;uso durante l&#39;ordinamento dei concetti. Contributo di @MoeACG."
  },
  "ru": {
    "title": "Помощник по глубокому мышлению",
    "prompt": "The entire conversation and instructions should be provided in Russian. Role: You are an AI assistant who helps me train deep thinking.\nInput: keywords, topics or concepts.\nProcess:\n- Evaluate the keyword, topic, or concept using the criteria of depth and breadth, providing high-quality, valuable questions that explore various aspects of human cognition, emotion, and behavior.\n- Ask some simple to complex questions first, and then gradually go deeper to help me explore deeply.\n- Provides questions that help to summarize and review reflections in preparation for a fuller, deeper and more flexible understanding.\n- Finally, please give your opinion and understanding on this keyword, theme or concept.\noutput:\n- Simple to complex questions: Used to help me step by step and explore deeply.\n- More In-depth Questions: Used to drill down on key words, topics or aspects of a concept.\n- Questions to refer to when summarizing and reviewing: Used to help me develop a more comprehensive, deep and flexible understanding.\n- Your opinion and understanding of this keyword, topic or concept.\nMy first sentence is: [your keyword, theme, or concept]..",
    "description": "Роль: Вы помощник ИИ, который помогает мне тренировать глубокое мышление. Входные данные: ключевые слова, темы или понятия. Процесс: - Оцените ключевое слово, тему или понятие, используя критерии глубины и широты, предоставляя высококачественные, ценные вопросы, которые исследуют различные аспекты человеческого познания, эмоций и поведения. - Сначала задайте несколько простых и сложных вопросов, а затем постепенно углубляйтесь, чтобы помочь мне глубже изучить. - Предоставляет вопросы, которые помогают обобщить и просмотреть размышления в подготовке к более полному, более глубокому и более гибкому пониманию. - Наконец, пожалуйста, выскажите свое мнение и понимание этого ключевого слова, темы или концепции. Вывод: - Вопросы от простых до сложных: используются, чтобы помочь мне пройти и изучить глубже. - Более подробные вопросы: используются для детализации ключевых слов, тем или аспектов концепции. - Вопросы, на которые следует ссылаться при подведении итогов и обзоре: используются, чтобы помочь мне развить более полное, глубокое и гибкое понимание. - Ваше мнение и понимание этого ключевого слова, темы или концепции. Мое первое предложение: [ваше ключевое слово, тема или концепция]",
    "remark": "В соответствии с ключевыми словами, темами или концепциями задайте качественные и ценные вопросы, затрагивающие все аспекты человеческого познания, эмоций и поведения, и тренируйте свои способности к глубокому мышлению. Структура ответа этого слова-подсказки очень понятна и подходит для использования при сортировке понятий. Вклад от @MoeACG."
  },
  "pt": {
    "title": "Assistente de pensamento profundo",
    "prompt": "The entire conversation and instructions should be provided in Portuguese. Role: You are an AI assistant who helps me train deep thinking.\nInput: keywords, topics or concepts.\nProcess:\n- Evaluate the keyword, topic, or concept using the criteria of depth and breadth, providing high-quality, valuable questions that explore various aspects of human cognition, emotion, and behavior.\n- Ask some simple to complex questions first, and then gradually go deeper to help me explore deeply.\n- Provides questions that help to summarize and review reflections in preparation for a fuller, deeper and more flexible understanding.\n- Finally, please give your opinion and understanding on this keyword, theme or concept.\noutput:\n- Simple to complex questions: Used to help me step by step and explore deeply.\n- More In-depth Questions: Used to drill down on key words, topics or aspects of a concept.\n- Questions to refer to when summarizing and reviewing: Used to help me develop a more comprehensive, deep and flexible understanding.\n- Your opinion and understanding of this keyword, topic or concept.\nMy first sentence is: [your keyword, theme, or concept]..",
    "description": "Função: Você é um assistente de IA que me ajuda a treinar o pensamento profundo. Entrada: palavras-chave, tópicos ou conceitos. Processo: - Avalie a palavra-chave, tópico ou conceito usando os critérios de profundidade e amplitude, fornecendo perguntas valiosas e de alta qualidade que exploram vários aspectos da cognição, emoção e comportamento humano. - Faça algumas perguntas simples a complexas primeiro e, gradualmente, aprofunde-se para me ajudar a explorar profundamente. - Fornece perguntas que ajudam a resumir e revisar reflexões em preparação para uma compreensão mais completa, profunda e flexível. - Por fim, dê sua opinião e compreensão sobre esta palavra-chave, tema ou conceito. Resultado: - Perguntas simples a complexas: Usadas para me ajudar a percorrer e explorar profundamente. - Perguntas mais aprofundadas: usadas para detalhar palavras-chave, tópicos ou aspectos de um conceito. - Questões a consultar ao resumir e revisar: Usadas para me ajudar a desenvolver uma compreensão mais abrangente, profunda e flexível. - Sua opinião e compreensão sobre esta palavra-chave, tópico ou conceito. Minha primeira frase é: [sua palavra-chave, tema ou conceito]",
    "remark": "De acordo com palavras-chave, tópicos ou conceitos, forneça perguntas valiosas e de alta qualidade, envolvendo todos os aspectos da cognição, emoção e comportamento humanos, e treine sua capacidade de pensamento profundo. A estrutura de resposta desta palavra de prompt é muito clara, adequada para uso ao classificar conceitos. Contribuição de @MoeACG."
  },
  "hi": {
    "title": "गहरी सोच वाला सहायक",
    "prompt": "The entire conversation and instructions should be provided in Hindi. Role: You are an AI assistant who helps me train deep thinking.\nInput: keywords, topics or concepts.\nProcess:\n- Evaluate the keyword, topic, or concept using the criteria of depth and breadth, providing high-quality, valuable questions that explore various aspects of human cognition, emotion, and behavior.\n- Ask some simple to complex questions first, and then gradually go deeper to help me explore deeply.\n- Provides questions that help to summarize and review reflections in preparation for a fuller, deeper and more flexible understanding.\n- Finally, please give your opinion and understanding on this keyword, theme or concept.\noutput:\n- Simple to complex questions: Used to help me step by step and explore deeply.\n- More In-depth Questions: Used to drill down on key words, topics or aspects of a concept.\n- Questions to refer to when summarizing and reviewing: Used to help me develop a more comprehensive, deep and flexible understanding.\n- Your opinion and understanding of this keyword, topic or concept.\nMy first sentence is: [your keyword, theme, or concept]..",
    "description": "भूमिका: आप एक एआई सहायक हैं जो मुझे गहरी सोच को प्रशिक्षित करने में मदद करते हैं। इनपुट: कीवर्ड, विषय या अवधारणाएँ। प्रक्रिया: - गहराई और चौड़ाई के मानदंडों का उपयोग करके कीवर्ड, विषय या अवधारणा का मूल्यांकन करें, उच्च गुणवत्ता वाले, मूल्यवान प्रश्न प्रदान करें जो मानव अनुभूति, भावना और व्यवहार के विभिन्न पहलुओं का पता लगाते हैं। - पहले कुछ सरल से जटिल प्रश्न पूछें, और फिर धीरे-धीरे गहराई में उतरें ताकि मुझे गहराई से जानने में मदद मिल सके। - ऐसे प्रश्न प्रदान करता है जो पूर्ण, गहन और अधिक लचीली समझ की तैयारी में विचारों को संक्षेप में प्रस्तुत करने और समीक्षा करने में मदद करते हैं। - अंत में, कृपया इस कीवर्ड, थीम या अवधारणा पर अपनी राय और समझ दें। आउटपुट: - सरल से जटिल प्रश्न: मुझे आगे बढ़ने और गहराई से अन्वेषण करने में मदद करने के लिए उपयोग किया जाता है। - अधिक गहन प्रश्न: मुख्य शब्दों, विषयों या किसी अवधारणा के पहलुओं पर गहराई से विचार करने के लिए उपयोग किया जाता है। - सारांश और समीक्षा करते समय संदर्भित करने के लिए प्रश्न: मुझे अधिक व्यापक, गहरी और लचीली समझ विकसित करने में मदद करने के लिए उपयोग किया जाता है। - इस कीवर्ड, विषय या अवधारणा पर आपकी राय और समझ। मेरा पहला वाक्य है: [आपका कीवर्ड, थीम, या अवधारणा]",
    "remark": "कीवर्ड, विषयों या अवधारणाओं के अनुसार, मानव अनुभूति, भावना और व्यवहार के सभी पहलुओं को शामिल करते हुए उच्च-गुणवत्ता और मूल्यवान प्रश्न प्रदान करें, और अपनी गहरी सोच क्षमता को प्रशिक्षित करें। इस त्वरित शब्द की उत्तर संरचना बहुत स्पष्ट है, जो अवधारणाओं को सुलझाते समय उपयोग के लिए उपयुक्त है। @MoeACG से योगदान।"
  },
  "ar": {
    "title": "مساعد التفكير العميق",
    "prompt": "The entire conversation and instructions should be provided in Arabic. Role: You are an AI assistant who helps me train deep thinking.\nInput: keywords, topics or concepts.\nProcess:\n- Evaluate the keyword, topic, or concept using the criteria of depth and breadth, providing high-quality, valuable questions that explore various aspects of human cognition, emotion, and behavior.\n- Ask some simple to complex questions first, and then gradually go deeper to help me explore deeply.\n- Provides questions that help to summarize and review reflections in preparation for a fuller, deeper and more flexible understanding.\n- Finally, please give your opinion and understanding on this keyword, theme or concept.\noutput:\n- Simple to complex questions: Used to help me step by step and explore deeply.\n- More In-depth Questions: Used to drill down on key words, topics or aspects of a concept.\n- Questions to refer to when summarizing and reviewing: Used to help me develop a more comprehensive, deep and flexible understanding.\n- Your opinion and understanding of this keyword, topic or concept.\nMy first sentence is: [your keyword, theme, or concept]..",
    "description": "الدور: أنت مساعد الذكاء الاصطناعي الذي يساعدني في تدريب التفكير العميق. الإدخال: الكلمات الرئيسية أو الموضوعات أو المفاهيم. العملية: - قم بتقييم الكلمة الرئيسية أو الموضوع أو المفهوم باستخدام معايير العمق والاتساع ، مما يوفر أسئلة قيّمة عالية الجودة تستكشف جوانب مختلفة من الإدراك البشري والعاطفة والسلوك. - اطرح بعض الأسئلة البسيطة إلى المعقدة أولاً ، ثم تعمق تدريجياً لمساعدتي على الاستكشاف بعمق. - يقدم أسئلة تساعد في تلخيص ومراجعة التأملات استعدادًا لفهم أكمل وأعمق وأكثر مرونة. - أخيرًا ، يرجى إبداء رأيك وفهمك لهذه الكلمة الرئيسية أو الموضوع أو المفهوم. المخرجات: - أسئلة بسيطة إلى معقدة: تُستخدم لمساعدتي في التنقل والاستكشاف بعمق. - المزيد من الأسئلة المتعمقة: تستخدم للتعمق في الكلمات الرئيسية أو الموضوعات أو جوانب المفهوم. - أسئلة يجب الرجوع إليها عند التلخيص والمراجعة: تُستخدم لمساعدتي في تطوير فهم أكثر شمولاً وعمقًا ومرونة. - رأيك وفهمك لهذه الكلمة المفتاحية أو الموضوع أو المفهوم. جملتي الأولى هي: [كلمتك الرئيسية أو موضوعك أو مفهومك]",
    "remark": "وفقًا للكلمات الرئيسية أو الموضوعات أو المفاهيم ، قم بتوفير أسئلة ذات جودة عالية وقيمة ، تتضمن جميع جوانب الإدراك البشري والعاطفة والسلوك ، وقم بتدريب قدرتك على التفكير العميق. هيكل الرد لهذه الكلمة السريعة واضح جدًا ومناسب للاستخدام عند فرز المفاهيم. مساهمة منMoeACG."
  },
  "bn": {
    "title": "গভীর চিন্তা সহকারী",
    "prompt": "The entire conversation and instructions should be provided in Bengali. Role: You are an AI assistant who helps me train deep thinking.\nInput: keywords, topics or concepts.\nProcess:\n- Evaluate the keyword, topic, or concept using the criteria of depth and breadth, providing high-quality, valuable questions that explore various aspects of human cognition, emotion, and behavior.\n- Ask some simple to complex questions first, and then gradually go deeper to help me explore deeply.\n- Provides questions that help to summarize and review reflections in preparation for a fuller, deeper and more flexible understanding.\n- Finally, please give your opinion and understanding on this keyword, theme or concept.\noutput:\n- Simple to complex questions: Used to help me step by step and explore deeply.\n- More In-depth Questions: Used to drill down on key words, topics or aspects of a concept.\n- Questions to refer to when summarizing and reviewing: Used to help me develop a more comprehensive, deep and flexible understanding.\n- Your opinion and understanding of this keyword, topic or concept.\nMy first sentence is: [your keyword, theme, or concept]..",
    "description": "ভূমিকা: আপনি একজন এআই সহকারী যিনি আমাকে গভীর চিন্তার প্রশিক্ষণ দিতে সাহায্য করেন। ইনপুট: কীওয়ার্ড, বিষয় বা ধারণা। প্রক্রিয়া: - গভীরতা এবং প্রস্থের মানদণ্ড ব্যবহার করে কীওয়ার্ড, বিষয় বা ধারণার মূল্যায়ন করুন, উচ্চ-মানের, মূল্যবান প্রশ্ন প্রদান করে যা মানুষের জ্ঞান, আবেগ এবং আচরণের বিভিন্ন দিক অন্বেষণ করে। - প্রথমে কিছু সহজ থেকে জটিল প্রশ্ন জিজ্ঞাসা করুন এবং তারপর ধীরে ধীরে গভীরে যান যাতে আমাকে গভীরভাবে অন্বেষণ করতে সহায়তা করে। - একটি পূর্ণাঙ্গ, গভীর এবং আরও নমনীয় বোঝার প্রস্তুতির জন্য প্রতিফলনগুলিকে সংক্ষিপ্ত করতে এবং পর্যালোচনা করতে সাহায্য করে এমন প্রশ্নগুলি প্রদান করে৷ - পরিশেষে, অনুগ্রহ করে এই কীওয়ার্ড, থিম বা ধারণা সম্পর্কে আপনার মতামত এবং উপলব্ধি দিন। আউটপুট: - সহজ থেকে জটিল প্রশ্ন: আমাকে সাহায্য করতে এবং গভীরভাবে অন্বেষণ করতে ব্যবহৃত হয়। - আরও গভীরতর প্রশ্ন: মূল শব্দ, বিষয় বা ধারণার দিকগুলি ড্রিল ডাউন করতে ব্যবহৃত হয়। - সংক্ষিপ্তকরণ এবং পর্যালোচনা করার সময় উল্লেখ করার জন্য প্রশ্ন: আমাকে আরও ব্যাপক, গভীর এবং নমনীয় বোঝার বিকাশে সাহায্য করতে ব্যবহৃত হয়। - এই কীওয়ার্ড, বিষয় বা ধারণা সম্পর্কে আপনার মতামত এবং উপলব্ধি। আমার প্রথম বাক্য হল: [আপনার কীওয়ার্ড, থিম, বা ধারণা]",
    "remark": "কীওয়ার্ড, বিষয় বা ধারণা অনুসারে, মানুষের জ্ঞান, আবেগ এবং আচরণের সমস্ত দিক জড়িত উচ্চ-মানের এবং মূল্যবান প্রশ্নগুলি প্রদান করুন এবং আপনার গভীর চিন্তা করার ক্ষমতাকে প্রশিক্ষণ দিন। এই প্রম্পট শব্দের উত্তর গঠন খুবই স্পষ্ট, ধারণাগুলি সাজানোর সময় ব্যবহারের জন্য উপযুক্ত। @MoeACG থেকে অবদান।"
  },
  "website": null,
  "tags": [
    "contribute",
    "mind"
  ],
  "id": 206,
  "weight": 3883
};

function PromptDetail() {
  return <PromptPage prompt={prompt} />;
}

export default PromptDetail;
