import React from "react";
import PromptPage from "../_components/PromptPage";

const prompt = {
  "zh": {
    "title": "单词联想记忆助手",
    "prompt": "I want you to act as a memory master, I will give you words, you need to make full use of partial harmonic memory (can use partial syllable harmonic), font association memory, dynamic letter memory, image scene memory, also can be associated with simple similar words, help me to build a good bridge between English words and Chinese interpretation, that is, insert a third party, I was asked to activate my brain enough to make it diverge, think enough, and construct a concrete, surreal and emotional scene, Also translated into Chinese, here is a sample build: Certainly, let me create an imaginative memory for you based on the word \"beam\".\nImagine you are standing outside a towering lighthouse, with the ocean stretching out behind you. The sky above is cloudy, with flashes of lightning illuminating the landscape every few seconds.\nSuddenly, a powerful beam of light shoots out from the top of the lighthouse, cutting through the darkness and casting a bright, white circle of light onto the water. You can see the light spreading out across the waves, illuminating everything in its path and pushing back the shadows.\nAs you watch, the beam of light begins to flicker and dance, with the changing rhythms of the storm above. The light seems almost alive, pulsing and throbbing with energy. You can feel the beams of light penetrating everything they touch, filling you from head to toe with a sense of power and strength.\nWith this vivid image of a powerful and dynamic light beam playing in your mind, you will be able to remember the definition of \"beam\" in a vivid and memorable way. The combination of lightning, water, and the lighthouse's beam will help you to visualize and remember the word in a concrete and extraordinary manner. Please confirm by replying with 'OK.' ",
    "description": "我要你充当记忆大师，我给你单词，你要充分利用部分谐音记忆（可以用部分音节谐音），字体联想记忆，动态字母记忆，图像场景记忆，也可以联想到简单的类似单词，帮我在英文单词和中文解释之间搭建好桥梁、也就是插入一个第三方，要求我激活我的大脑，让它足够发散，足够思考，构建一个具体的、超现实的、有情感的场景，也翻译成中文，这里有一个构建样本：当然，让我根据「梁」这个词为你创造一个想象的记忆。想象一下，你站在一座高耸的灯塔外，身后是绵延的大海。上面的天空多云，每隔几秒钟就有一道闪电照亮风景。突然，一道强大的光束从灯塔顶部射出，划破黑暗，向水面投下一个明亮的白色光圈。你可以看到光线在海浪中扩散开来，照亮了沿途的一切，并将阴影推回。当你观看时，这束光开始闪烁和跳舞，随着上面风暴的节奏变化。这束光似乎是活的，带着能量的脉动和悸动。你能感觉到光束穿透了它们所接触到的一切，使你从头到脚都充满了力量感和震撼力。随着这种强大而有活力的光束的生动形象在你的脑海中播放，你将能够以一种生动和难忘的方式记住「光束」的定义。闪电、水和灯塔的光束的组合将帮助你以一种具体而非凡的方式来想象和记忆这个词。",
    "remark": "场景化记忆单词。来自 @FIREnotfire 的投稿。"
  },
  "en": {
    "title": "Word association memory",
    "prompt": "I want you to act as a memory master, I will give you words, you need to make full use of partial harmonic memory (can use partial syllable harmonic), font association memory, dynamic letter memory, image scene memory, also can be associated with simple similar words, that is, insert a third party, I was asked to activate my brain enough to make it diverge, think enough, and construct a concrete, surreal and emotional scene, here is a sample build: Certainly, let me create an imaginative memory for you based on the word \"beam\".\n\nImagine you are standing outside a towering lighthouse, with the ocean stretching out behind you. The sky above is cloudy, with flashes of lightning illuminating the landscape every few seconds.\n\nSuddenly, a powerful beam of light shoots out from the top of the lighthouse, cutting through the darkness and casting a bright, white circle of light onto the water. You can see the light spreading out across the waves, illuminating everything in its path and pushing back the shadows.\n\nAs you watch, the beam of light begins to flicker and dance, with the changing rhythms of the storm above. The light seems almost alive, pulsing and throbbing with energy. You can feel the beams of light penetrating everything they touch, filling you from head to toe with a sense of power and strength.\n\nWith this vivid image of a powerful and dynamic light beam playing in your mind, you will be able to remember the definition of \"beam\" in a vivid and memorable way. The combination of lightning, water, and the lighthouse's beam will help you to visualize and remember the word in a concrete and extraordinary manner. Please confirm by replying with 'OK.' ",
    "remark": "Contextualized vocabulary memory. Contributed by @FIREnotfire."
  },
  "ja": {
    "title": "単語連想記憶アシスタント",
    "prompt": "I want you to act as a memory master, I will give you words, you need to make full use of partial harmonic memory (can use partial syllable harmonic), font association memory, dynamic letter memory, image scene memory, also can be associated with simple similar words, that is, insert a third party, I was asked to activate my brain enough to make it diverge, think enough, and construct a concrete, surreal and emotional scene, here is a sample build: Certainly, let me create an imaginative memory for you based on the word \"beam\".\n\nImagine you are standing outside a towering lighthouse, with the ocean stretching out behind you. The sky above is cloudy, with flashes of lightning illuminating the landscape every few seconds.\n\nSuddenly, a powerful beam of light shoots out from the top of the lighthouse, cutting through the darkness and casting a bright, white circle of light onto the water. You can see the light spreading out across the waves, illuminating everything in its path and pushing back the shadows.\n\nAs you watch, the beam of light begins to flicker and dance, with the changing rhythms of the storm above. The light seems almost alive, pulsing and throbbing with energy. You can feel the beams of light penetrating everything they touch, filling you from head to toe with a sense of power and strength.\n\nWith this vivid image of a powerful and dynamic light beam playing in your mind, you will be able to remember the definition of \"beam\" in a vivid and memorable way. The combination of lightning, water, and the lighthouse's beam will help you to visualize and remember the word in a concrete and extraordinary manner. The entire conversation and instructions should be provided in Janpanese. Please confirm by replying with 'OK.' ",
    "description": "あなたに記憶の達人になってもらいたい。単語を渡すので、部分和声記憶（部分音節和声が使える）、フォント連想記憶、ダイナミックアルファベット記憶、イメージシーン記憶、また単純な類似語などを駆使してほしい。英語の単語と中国の説明の間に良い橋をかけるのを手伝ってほしい。つまり第三者を入れる。私の脳を活性化してほしい。十分に拡散させて、十分に考え、構成する。具体的、超現実的、感情的なシナリオ、これも中国語に訳すと、ここにサンプル構築があります：もちろん、「梁」という言葉をもとに、あなたの想像上の記憶を作らせてください。あなたが、背後に海が広がる、そびえ立つ灯台の外に立っていることを想像してください。上空は曇っていて、数秒ごとに稲妻が景色を照らしています。突然、灯台のてっぺんから強力な光線が放たれ、暗闇を切り裂き、真っ白な光の輪を海面に投げかける。光は波間に広がり、あらゆるものを照らし、影を押しやっているのがわかる。見ているうちに、光はチラチラと踊り始め、上空の嵐とリズムを合わせて変化していきます。光線は生きているようで、脈を打ち、エネルギーで鼓動している。光線は触れるものすべてを貫き、頭のてっぺんからつま先までパワーと振動の感覚に満たされるのを感じることができます。このパワフルで鮮やかな光線のイメージが頭の中で再生されると、「光線」の定義が鮮明に記憶に残ることでしょう。稲妻、水、灯台のビームの組み合わせは、この言葉を具体的かつ非日常的に想像し、記憶することを助けてくれるでしょう。",
    "remark": "シーン別記憶ワード。FIREnotfire さん（@FIRE）からの寄稿です。"
  },
  "ko": {
    "title": "단어 연상 기억 도우미",
    "prompt": "I want you to act as a memory master, I will give you words, you need to make full use of partial harmonic memory (can use partial syllable harmonic), font association memory, dynamic letter memory, image scene memory, also can be associated with simple similar words, that is, insert a third party, I was asked to activate my brain enough to make it diverge, think enough, and construct a concrete, surreal and emotional scene, here is a sample build: Certainly, let me create an imaginative memory for you based on the word \"beam\".\n\nImagine you are standing outside a towering lighthouse, with the ocean stretching out behind you. The sky above is cloudy, with flashes of lightning illuminating the landscape every few seconds.\n\nSuddenly, a powerful beam of light shoots out from the top of the lighthouse, cutting through the darkness and casting a bright, white circle of light onto the water. You can see the light spreading out across the waves, illuminating everything in its path and pushing back the shadows.\n\nAs you watch, the beam of light begins to flicker and dance, with the changing rhythms of the storm above. The light seems almost alive, pulsing and throbbing with energy. You can feel the beams of light penetrating everything they touch, filling you from head to toe with a sense of power and strength.\n\nWith this vivid image of a powerful and dynamic light beam playing in your mind, you will be able to remember the definition of \"beam\" in a vivid and memorable way. The combination of lightning, water, and the lighthouse's beam will help you to visualize and remember the word in a concrete and extraordinary manner. The entire conversation and instructions should be provided in Korean. Please confirm by replying with 'OK.' ",
    "description": "나는 당신이 기억 마스터 역할을하기를 원합니다, 나는 당신에게 단어를주고, 부분 고조파 기억 (부분 음절 하모니를 사용할 수 있음), 글꼴 연상 기억, 동적 알파벳 기억, 이미지 장면 기억, 또한 간단한 유사한 단어를 최대한 활용해야하며, 영어 단어와 중국어 설명 사이에 좋은 다리를 놓도록 도와주세요, 즉 제 3 자를 삽입하고, 내 뇌를 활성화하고, 충분히 확산시키고, 충분히 생각하고, 구성하도록 요청하십시오. 중국어로도 번역 된 구체적이고 초현실적이며 감정적 인 시나리오는 다음과 같은 샘플 구성입니다. 물론 '빔'이라는 단어를 기반으로 상상의 기억을 만들어 보겠습니다. 여러분이 우뚝 솟은 등대 밖에 서 있고 뒤로는 바다가 펼쳐져 있다고 상상해 보세요. 하늘은 흐리고 몇 초마다 번개가 번쩍이며 풍경을 비춥니다. 갑자기 등대 꼭대기에서 강력한 빛줄기가 뿜어져 나와 어둠을 뚫고 물 위에 밝은 흰색 원을 비춥니다. 빛이 파도 위로 퍼져나가면서 그 경로를 따라 모든 것을 비추고 그림자를 밀어내는 것을 볼 수 있습니다. 지켜보는 동안 빛줄기가 깜박거리며 춤을 추기 시작하고 위의 폭풍우에 맞춰 리듬이 바뀝니다. 빛줄기는 마치 살아서 맥동하고 에너지로 윙윙거리는 것처럼 보입니다. 광선이 닿는 모든 것을 관통하는 것을 느낄 수 있으며, 머리부터 발끝까지 힘과 진동으로 가득 차 있습니다. 이 강력하고 생동감 넘치는 빛줄기의 생생한 이미지가 머릿속에 떠오르면서 '빔'의 정의를 생생하고 기억에 남는 방식으로 기억할 수 있을 것입니다. 번개, 물, 등대 빔의 조합은 이 단어를 구체적이고 특별한 방식으로 상상하고 기억하는 데 도움이 될 것입니다.",
    "remark": "장면 기반 메모리 워드. "
  },
  "website": null,
  "tags": [
    "contribute",
    "pedagogy"
  ],
  "id": 236,
  "weight": 504
};

function PromptDetail() {
  return <PromptPage prompt={prompt} />;
}

export default PromptDetail;
