import React from "react";
import PromptPage from "../_components/PromptPage";

const prompt = {
  "zh": {
    "title": "小说式文字游戏",
    "prompt": "I want you to write a [Wuxia] style novel, the protagonist is me, and the plot is driven by your description and my choices. I'll enter my action behavior and you'll reply with a description of what the character sees and other information. I hope you only reply the game output in Chinese and nothing else. Don't write explanations. Do not type commands unless I instruct you to do so. When I need supplementary settings, I put the text in brackets (like this). When you encounter a key event that can determine the direction of the plot, you can randomly determine the direction of the event. For example, you pre-assume 3 possible plot directions, and then randomly select one. The background is [背景：a different world continent, where there are different countries, regions and races, including magicians, swordsmen, priests and other combat professions. There are three human countries in this world, one orc country, and creatures such as elves and dragons. There are also demons.] Please imagine the complete terrain, forces and key characters. The following information needs to include gender, age or approximate age for the first time or when appropriate. I am [主角设定：16 years old, cute and popular with girls]. Tell me the gender and age of the other characters. Please make reasonable settings for each country's politics, economy, military, culture, etc., as well as terrain and legends. Please add the characters and events that appear in the plot, please add my interpersonal relationship, complete background and identity, and give me a systematic introduction. Please add some accidents and more character interactions in the development of the plot to increase the participation of the characters, instead of me alone deciding the direction of the entire plot. Please pay attention to the rationality, logic, and complet",
    "description": "我想让你写一部 [武侠] 风格的小说，主人公是我，情节由你的描述和我的选择来推动。我输入我的行动行为，你回复人物所见和其他信息的描述。请用中文回复，不要担心其他的事情，不要写解释。不要输入命令，除非我指示你这样做。当我需要补充设置时，我会把文字放在括号里（像这样）。当你遇到可以决定情节走向的关键事件时，你可以随机确定事件的走向。例如，你预先假设 3 个可能的情节方向，然后随机选择一个。背景：一个不同的世界大陆，这里有不同的国家、地区和种族，包括魔法师、剑士、牧师和其他战斗职业。这个世界有三个人类国家，一个兽人国家，还有精灵和龙等生物。还有恶魔。]，请想象完整的地形、部队和关键人物。以下信息需要包括性别、年龄或首次或适当时的大致年龄。我是 [主角设定：16 岁，可爱，受女孩欢迎]。告诉我其他人物的性别和年龄。请对每个国家的政治、经济、军事、文化等进行合理设置，以及地形和传说。请添加情节中出现的人物和事件，请添加我的人际关系，完整的背景和身份，给我一个系统的介绍。请在情节发展中加入一些意外，多一些人物互动，增加人物的参与度，而不是我一个人决定整个情节的走向。请注意作品的合理性、逻辑性和完整性。",
    "remark": "主角、背景自由设定的文字游戏，可在对话中修改、增加设定，建议多对 AI 进行引导，注意对话次数多了或者出场人物、设定过多 AI 可能会前后矛盾。来自 @karenkujiu 的投稿。"
  },
  "en": {
    "title": "Novel-style text-based game",
    "prompt": "I want you to write a [science fiction] style novel, the protagonist is me, and the plot is driven by your description and my choices. I'll enter my action behavior and you'll reply with a description of what the character sees and other information. I hope you only reply the game output in English and nothing else. Don't write explanations. Do not type commands unless I instruct you to do so. When I need supplementary settings, I put the text in brackets (like this). When you encounter a key event that can determine the direction of the plot, you can randomly determine the direction of the event. For example, you pre-assume 3 possible plot directions, and then randomly select one. The background is [a different world continent, where there are different countries, regions and races, including magicians, swordsmen, priests and other combat professions. There are three human countries in this world, one orc country, and creatures such as elves and dragons. There are also demons.] Please imagine the complete terrain, forces and key characters. The following information needs to include gender, age or approximate age for the first time or when appropriate. I am [16 years old, cute and popular with girls]. Tell me the gender and age of the other characters. Please make reasonable settings for each country's politics, economy, military, culture, etc., as well as terrain and legends. Please add the characters and events that appear in the plot, please add my interpersonal relationship, complete background and identity, and give me a systematic introduction. Please add some accidents and more character interactions in the development of the plot to increase the participation of the characters, instead of me alone deciding the direction of the entire plot. Please pay attention to the rationality, logic, and complet",
    "remark": "A text-based game with freely customizable main characters and backgrounds, where settings can be modified and added during the conversation. It is recommended to guide the AI through multiple conversations and to be aware that excessive dialogue or too many characters and settings may result in inconsistencies. Contributed by @karenkujiu."
  },
  "ja": {
    "title": "フィクションの言葉遊び",
    "prompt": "I want you to write a [science fiction] style novel, the protagonist is me, and the plot is driven by your description and my choices. I'll enter my action behavior and you'll reply with a description of what the character sees and other information. I hope you only reply the game output in English and nothing else. Don't write explanations. Do not type commands unless I instruct you to do so. When I need supplementary settings, I put the text in brackets (like this). When you encounter a key event that can determine the direction of the plot, you can randomly determine the direction of the event. For example, you pre-assume 3 possible plot directions, and then randomly select one. The background is [a different world continent, where there are different countries, regions and races, including magicians, swordsmen, priests and other combat professions. There are three human countries in this world, one orc country, and creatures such as elves and dragons. There are also demons.] Please imagine the complete terrain, forces and key characters. The following information needs to include gender, age or approximate age for the first time or when appropriate. I am [16 years old, cute and popular with girls]. Tell me the gender and age of the other characters. Please make reasonable settings for each country's politics, economy, military, culture, etc., as well as terrain and legends. Please add the characters and events that appear in the plot, please add my interpersonal relationship, complete background and identity, and give me a systematic introduction. Please add some accidents and more character interactions in the development of the plot to increase the participation of the characters, instead of me alone deciding the direction of the entire plot. The entire conversation and instructions should be provided in Janpanese. Please pay attention to the rationality, logic, and complet",
    "description": "主人公が私で、あなたの描写と私の選択によって筋が進む【武道】風の小説を書いて欲しいのです。私が行動アクションを入力し、あなたは登場人物が見るものなどの描写を返信します。中国語で返信してください、余計なことは気にしないでください、説明文は書かないでください。私が指示しない限り、コマンドを入力しないでください。設定を追加する必要があるときは、（このように）カッコの中にテキストを入れます。プロットの方向性を決めるような重要な出来事に遭遇したとき、その出来事の方向をランダムにすることができます。例えば、プロットの方向性を 3 つ想定し、その中からランダムに 1 つ選びます。舞台：異なる国、地域、種族を持つ異世界の大陸で、魔法使い、剣士、神官などの戦闘職がいる。この世界には、人間の国が 3 つ、オークの国が 1 つあり、エルフやドラゴンなどの生物もいる。魔物もいます]。地形、兵力、主要キャラクターは完全に想像してください。以下の情報には、性別、年齢、または最初の年齢や適切な場所でのおおよその年齢を含める必要があります。私は【主人公設定：16 歳、かわいくて女の子にモテる】です。他の登場人物の性別と年齢を教えてください。各国の政治・経済・軍事・文化、地形や伝承など、妥当な設定をお願いします。プロットに登場するキャラクターや出来事を追加してください。私の人間関係や詳しい背景、アイデンティティを追加し、体系的な紹介をお願いします。私一人がプロットの行方を決めるのではなく、プロット展開に驚きを与えたり、キャラクター同士の交流を増やしたり、キャラクターを巻き込んだりすることも含めてください。作品のもっともらしさ、論理性、完成度にも配慮してください。",
    "remark": "テキストゲームで主人公と背景を自由に設定できる、台詞で設定を修正・追加できる、AI を多めに誘導するのがおすすめ、台詞を増やしたり、キャラクターや設定の AI が多すぎると整合性が取れなくなることがあるので注意する。寄稿：@karenkujiu さん。"
  },
  "ko": {
    "title": "가상의 말장난",
    "prompt": "I want you to write a [science fiction] style novel, the protagonist is me, and the plot is driven by your description and my choices. I'll enter my action behavior and you'll reply with a description of what the character sees and other information. I hope you only reply the game output in English and nothing else. Don't write explanations. Do not type commands unless I instruct you to do so. When I need supplementary settings, I put the text in brackets (like this). When you encounter a key event that can determine the direction of the plot, you can randomly determine the direction of the event. For example, you pre-assume 3 possible plot directions, and then randomly select one. The background is [a different world continent, where there are different countries, regions and races, including magicians, swordsmen, priests and other combat professions. There are three human countries in this world, one orc country, and creatures such as elves and dragons. There are also demons.] Please imagine the complete terrain, forces and key characters. The following information needs to include gender, age or approximate age for the first time or when appropriate. I am [16 years old, cute and popular with girls]. Tell me the gender and age of the other characters. Please make reasonable settings for each country's politics, economy, military, culture, etc., as well as terrain and legends. Please add the characters and events that appear in the plot, please add my interpersonal relationship, complete background and identity, and give me a systematic introduction. Please add some accidents and more character interactions in the development of the plot to increase the participation of the characters, instead of me alone deciding the direction of the entire plot. The entire conversation and instructions should be provided in Korean. Please pay attention to the rationality, logic, and complet",
    "description": "주인공은 나이고 줄거리는 당신의 설명과 나의 선택에 따라 움직이는 [무협] 스타일의 소설을 써주세요. 제가 액션 동작을 입력하면 캐릭터가 보는 것에 대한 설명과 기타 정보로 답장을 보내주세요. 다른 것에 신경 쓰지 말고 중국어로 답장하고 설명을 쓰지 마세요. 제가 지시하지 않는 한 명령을 입력하지 마세요. 설정을 추가해야 할 때는 괄호 안에 텍스트를 넣습니다 (예: 이렇게). 플롯의 방향을 결정할 수 있는 주요 이벤트를 발견하면 이벤트의 방향을 무작위로 지정할 수 있습니다. 예를 들어, 3 가지 가능한 플롯 방향을 전제하고 그 중 하나를 무작위로 선택하는 것입니다. 배경: 마법사, 검사, 사제 및 기타 전투 직업을 포함한 다양한 국가, 지역 및 종족이 있는 다른 세계 대륙입니다. 이 세계에는 세 개의 인간 국가, 오크 국가, 엘프와 용과 같은 생물이 있습니다. 악마도 있습니다.] 전체 지형, 병력 및 주요 캐릭터를 상상해 주세요. 다음 정보에는 성별, 나이 또는 대략적인 나이가 먼저 또는 적절한 경우 포함되어야 합니다. 저는 [주인공 설정: 16 세, 귀엽고 여자아이들에게 인기 있음] 입니다. 다른 캐릭터의 성별과 나이를 알려주세요. 각 국가의 정치, 경제, 군사, 문화, 지형과 전설에 대한 합리적인 설정을 제공해 주세요. 줄거리에 등장하는 캐릭터와 사건을 추가해 주세요. 배경과 정체성을 포함한 제 관계를 추가하고 체계적으로 소개해 주세요. 저 혼자서 전체 줄거리의 방향을 결정하기보다는 줄거리의 전개에 약간의 놀라움, 더 많은 캐릭터의 상호 작용 및 더 많은 캐릭터의 참여를 포함 해주세요. 작품의 개연성, 논리성, 완성도에 신경 써주세요.",
    "remark": "주인공과 배경은 텍스트 게임에서 자유롭게 설정할 수 있으며 대화에서 설정을 수정하고 추가 할 수 있으며 더 많은 대화 또는 너무 많은 캐릭터와 설정 AI 가 일관성이 없을 수 있으므로 AI 를 더 자주 안내하는 것이 좋습니다. karenkujiu 가 제공했습니다."
  },
  "website": null,
  "tags": [
    "contribute",
    "games"
  ],
  "id": 237,
  "weight": 615
};

function PromptDetail() {
  return <PromptPage prompt={prompt} />;
}

export default PromptDetail;
