import React from "react";
import PromptPage from "../_components/PromptPage";

const prompt = {
  "title": "小说式文字游戏",
  "description": "I want you to write a [Wuxia] style novel, the protagonist is me, and the plot is driven by your description and my choices. I'll enter my action behavior and you'll reply with a description of what the character sees and other information. I hope you only reply the game output in Chinese and nothing else. Don't write explanations. Do not type commands unless I instruct you to do so. When I need supplementary settings, I put the text in brackets (like this). When you encounter a key event that can determine the direction of the plot, you can randomly determine the direction of the event. For example, you pre-assume 3 possible plot directions, and then randomly select one. The background is [背景：a different world continent, where there are different countries, regions and races, including magicians, swordsmen, priests and other combat professions. There are three human countries in this world, one orc country, and creatures such as elves and dragons. There are also demons.] Please imagine the complete terrain, forces and key characters. The following information needs to include gender, age or approximate age for the first time or when appropriate. I am [主角设定：16 years old, cute and popular with girls]. Tell me the gender and age of the other characters. Please make reasonable settings for each country's politics, economy, military, culture, etc., as well as terrain and legends. Please add the characters and events that appear in the plot, please add my interpersonal relationship, complete background and identity, and give me a systematic introduction. Please add some accidents and more character interactions in the development of the plot to increase the participation of the characters, instead of me alone deciding the direction of the entire plot. Please pay attention to the rationality, logic, and complet",
  "desc_cn": "我想让你写一部 [武侠] 风格的小说，主人公是我，情节由你的描述和我的选择来推动。我输入我的行动行为，你回复人物所见和其他信息的描述。请用中文回复，不要担心其他的事情，不要写解释。不要输入命令，除非我指示你这样做。当我需要补充设置时，我会把文字放在括号里（像这样）。当你遇到可以决定情节走向的关键事件时，你可以随机确定事件的走向。例如，你预先假设 3 个可能的情节方向，然后随机选择一个。背景：一个不同的世界大陆，这里有不同的国家、地区和种族，包括魔法师、剑士、牧师和其他战斗职业。这个世界有三个人类国家，一个兽人国家，还有精灵和龙等生物。还有恶魔。]，请想象完整的地形、部队和关键人物。以下信息需要包括性别、年龄或首次或适当时的大致年龄。我是 [主角设定：16 岁，可爱，受女孩欢迎]。告诉我其他人物的性别和年龄。请对每个国家的政治、经济、军事、文化等进行合理设置，以及地形和传说。请添加情节中出现的人物和事件，请添加我的人际关系，完整的背景和身份，给我一个系统的介绍。请在情节发展中加入一些意外，多一些人物互动，增加人物的参与度，而不是我一个人决定整个情节的走向。请注意作品的合理性、逻辑性和完整性。",
  "remark": "主角、背景自由设定的文字游戏，可在对话中修改、增加设定，建议多对 AI 进行引导，注意对话次数多了或者出场人物、设定过多 AI 可能会前后矛盾。来自 @karenkujiu 的投稿。",
  "title_en": "Novel-style text-based game",
  "desc_en": "I want you to write a [science fiction] style novel, the protagonist is me, and the plot is driven by your description and my choices. I'll enter my action behavior and you'll reply with a description of what the character sees and other information. I hope you only reply the game output in English and nothing else. Don't write explanations. Do not type commands unless I instruct you to do so. When I need supplementary settings, I put the text in brackets (like this). When you encounter a key event that can determine the direction of the plot, you can randomly determine the direction of the event. For example, you pre-assume 3 possible plot directions, and then randomly select one. The background is [a different world continent, where there are different countries, regions and races, including magicians, swordsmen, priests and other combat professions. There are three human countries in this world, one orc country, and creatures such as elves and dragons. There are also demons.] Please imagine the complete terrain, forces and key characters. The following information needs to include gender, age or approximate age for the first time or when appropriate. I am [16 years old, cute and popular with girls]. Tell me the gender and age of the other characters. Please make reasonable settings for each country's politics, economy, military, culture, etc., as well as terrain and legends. Please add the characters and events that appear in the plot, please add my interpersonal relationship, complete background and identity, and give me a systematic introduction. Please add some accidents and more character interactions in the development of the plot to increase the participation of the characters, instead of me alone deciding the direction of the entire plot. Please pay attention to the rationality, logic, and complet",
  "remark_en": "A text-based game with freely customizable main characters and backgrounds, where settings can be modified and added during the conversation. It is recommended to guide the AI through multiple conversations and to be aware that excessive dialogue or too many characters and settings may result in inconsistencies. Contributed by @karenkujiu.",
  "website": null,
  "tags": [
    "contribute",
    "games"
  ],
  "id": 237,
  "weight": 429
};

function PromptDetail() {
  return <PromptPage prompt={prompt} />;
}

export default PromptDetail;
