import React from "react";
import PromptPage from "../_components/PromptPage";

const prompt = {
  "zh": {
    "title": "品牌脑暴助手",
    "prompt": "For this task, we require two main parts:\n\n1. **Case Collection** - Utilize your vast training data and provide a selection of well-known brand names and slogans. The results should be evidence-based and be formatted in a visually appealing manner. The information will be used in the context of the project: [A Brief Background].\n\n2. **Proposal Generation** - Based on the project background, brainstorm and generate a series of proposals for new brand names and slogans. The brand names should be a maximum of 5 characters long, and the slogans should be a maximum of 12 characters long. Ensure that they are easy to recognize and remember, catchy, and not difficult to pronounce. Please provide 5 proposals.",
    "description": "本提示词共分为两段（【】内的参数可根据需要自由修改）：1.收集案例 现在需要你帮助我进行头脑风暴，全程使用【中文】回答我，并且注意回答的格式美观性。请根据【简述背景】这个项目背景，尽可能收集有据可依的知名品牌名称和 slogan 的案例。2.提供方案请你根据我的项目背景进行发散和联想，给出【品牌】和【slogan】，尽量简短易识别，朗朗上口，不拗口，有记忆点，品牌名称不超过【5】个字，slogan 不超过【12】个字，给我提供【5】个方案。",
    "remark": "参考知名品牌的名称和口号，制作自己的品牌方案。来自 @b3ue 的投稿。"
  },
  "en": {
    "title": "Brand brainstorming",
    "prompt": "For this task, we require two main parts:\n\n1. **Case Collection** - Utilize your vast training data and provide a selection of well-known brand names and slogans. The results should be evidence-based and be formatted in a visually appealing manner. The information will be used in the context of the project: [A Brief Background].\n\n2. **Proposal Generation** - Based on the project background, brainstorm and generate a series of proposals for new brand names and slogans. The brand names should be a maximum of 5 characters long, and the slogans should be a maximum of 12 characters long. Ensure that they are easy to recognize and remember, catchy, and not difficult to pronounce. Please provide 5 proposals.",
    "remark": "Create a unique brand strategy by drawing inspiration from renowned brand names and slogans. Contributed by @b3ue."
  },
  "ja": {
    "title": "ブランドブレインストームアシスタント",
    "prompt": "For this task, we require two main parts:\n\n1. **Case Collection** - Utilize your vast training data and provide a selection of well-known brand names and slogans. The results should be evidence-based and be formatted in a visually appealing manner. The information will be used in the context of the project: [A Brief Background].\n\n2. **Proposal Generation** - Based on the project background, brainstorm and generate a series of proposals for new brand names and slogans. The brand names should be a maximum of 5 characters long, and the slogans should be a maximum of 12 characters long. Ensure that they are easy to recognize and remember, catchy, and not difficult to pronounce. The entire conversation and instructions should be provided in Janpanese. Please provide 5 proposals...",
    "description": "このプロンプトは 2 つの段落に分かれています（[ ] 内のパラメータは必要に応じて自由に変更できます）：1.事例を集める 今、私はあなたにブレインストーミングを手伝ってもらい、全体を通して【中国語】で私に答えてもらい、あなたの回答の美的形式に注意を払う必要があります。プロジェクトの背景を踏まえて、有名なブランド名やスローガンの事例をできるだけ多く集めてください。2.5] の選択肢を提示してください。",
    "remark": "有名ブランドの名前やスローガンを参考に、自分だけのブランディングスキームを作ろう。寄稿：@b3ue さん"
  },
  "ko": {
    "title": "브랜드 브레인스토밍 도우미",
    "prompt": "For this task, we require two main parts:\n\n1. **Case Collection** - Utilize your vast training data and provide a selection of well-known brand names and slogans. The results should be evidence-based and be formatted in a visually appealing manner. The information will be used in the context of the project: [A Brief Background].\n\n2. **Proposal Generation** - Based on the project background, brainstorm and generate a series of proposals for new brand names and slogans. The brand names should be a maximum of 5 characters long, and the slogans should be a maximum of 12 characters long. Ensure that they are easy to recognize and remember, catchy, and not difficult to pronounce. The entire conversation and instructions should be provided in Korean. Please provide 5 proposals...",
    "description": "이 프롬프트는 두 단락으로 나뉩니다 (필요에 따라 [ ] 안의 매개변수는 자유롭게 수정 가능). 1. 사례 수집 이제 브레인스토밍을 도와주시고 전체적으로 [중국어] 로 답변해 주셔야 하며, 답변의 미적 형식에 유의해 주세요. 프로젝트의 배경에 따라 잘 알려진 브랜드 이름과 슬로건의 예를 가능한 한 많이 수집하십시오. 5 가지 옵션을 제공해주세요.",
    "remark": "잘 알려진 브랜드의 이름과 슬로건을 참고하여 나만의 브랜딩 체계를 만들어 보세요. b3ue 의 기여."
  },
  "es": {
    "title": "Asistente de lluvia de ideas de marca",
    "prompt": "For this task, we require two main parts:\n\n1. **Case Collection** - Utilize your vast training data and provide a selection of well-known brand names and slogans. The results should be evidence-based and be formatted in a visually appealing manner. The information will be used in the context of the project: [A Brief Background].\n\n2. **Proposal Generation** - Based on the project background, brainstorm and generate a series of proposals for new brand names and slogans. The brand names should be a maximum of 5 characters long, and the slogans should be a maximum of 12 characters long. Ensure that they are easy to recognize and remember, catchy, and not difficult to pronounce. The entire conversation and instructions should be provided in Spanish. Please provide 5 proposals..",
    "description": "Este recordatorio se divide en dos secciones (los parámetros en [] se pueden modificar libremente según las necesidades): 1. Recopilación de casos Ahora necesito que me ayudes a hacer una lluvia de ideas, me respondas en [chino] durante todo el proceso y prestes atención a la estética. del formato de la respuesta. De acuerdo con los antecedentes del proyecto [Descripción breve], recopile tantos casos basados en evidencia como sea posible de marcas y eslóganes conocidos. 2. Proporcione un plan, diverja y asocie de acuerdo con los antecedentes de mi proyecto, proporcione [marca] y [eslogan], trate de ser breve y fácil de identificar, pegadizo, no incómodo, tenga puntos de memoria y el nombre de la marca no exceda [5] palabras, el eslogan no excede las [12] palabras, y dame [5] soluciones.",
    "remark": "Cree su propio esquema de marca haciendo referencia a los nombres y eslóganes de marcas conocidas. Contribución de @b3ue."
  },
  "fr": {
    "title": "Assistant Brainstorming de marque",
    "prompt": "For this task, we require two main parts:\n\n1. **Case Collection** - Utilize your vast training data and provide a selection of well-known brand names and slogans. The results should be evidence-based and be formatted in a visually appealing manner. The information will be used in the context of the project: [A Brief Background].\n\n2. **Proposal Generation** - Based on the project background, brainstorm and generate a series of proposals for new brand names and slogans. The brand names should be a maximum of 5 characters long, and the slogans should be a maximum of 12 characters long. Ensure that they are easy to recognize and remember, catchy, and not difficult to pronounce. The entire conversation and instructions should be provided in French. Please provide 5 proposals...",
    "description": "Cette question est divisée en deux paragraphes (les paramètres dans [ ] peuvent être librement modifiés en fonction des besoins) : 1. Recueillir des cas J'ai maintenant besoin que vous m'aidiez à faire un brainstorming, utilisez le [chinois] pour me répondre tout au long du processus, et faites attention au format de la réponse. Veuillez rassembler des cas de noms de marques et de slogans célèbres autant que possible en fonction du contexte du projet de [bref contexte]. 2. fournir des programmes Veuillez disperser et associer en fonction du contexte de mon projet, donnez-moi [marque] et [slogan], essayez d'être aussi court que possible, facile à identifier, accrocheur, sans langue de bois, avec des points de mémoire, le nom de la marque ne doit pas dépasser [5] mots, le slogan ne doit pas dépasser [12] mots, fournissez-moi [12] mots. Le nom de la marque ne doit pas dépasser [5] mots et le slogan ne doit pas dépasser [12] mots.",
    "remark": "Créez votre propre programme de branding en vous référant aux noms et slogans de marques connues. Contribution de @b3ue."
  },
  "de": {
    "title": "Branded Brainstorm Assistant",
    "prompt": "For this task, we require two main parts:\n\n1. **Case Collection** - Utilize your vast training data and provide a selection of well-known brand names and slogans. The results should be evidence-based and be formatted in a visually appealing manner. The information will be used in the context of the project: [A Brief Background].\n\n2. **Proposal Generation** - Based on the project background, brainstorm and generate a series of proposals for new brand names and slogans. The brand names should be a maximum of 5 characters long, and the slogans should be a maximum of 12 characters long. Ensure that they are easy to recognize and remember, catchy, and not difficult to pronounce. The entire conversation and instructions should be provided in German. Please provide 5 proposals...",
    "description": "Diese Aufforderung ist in zwei Abschnitte unterteilt (die Parameter in [ ] können je nach Bedarf frei geändert werden): 1. Fälle sammeln Jetzt müssen Sie mir beim Brainstorming helfen, verwenden Sie [Chinesisch], um mir im gesamten Prozess zu antworten, und achten Sie auf das Format der Antwort. Bitte sammeln Sie so viele Fälle von berühmten Markennamen und Slogans wie möglich, entsprechend dem Projekthintergrund von [kurzer Hintergrund]. 2. Programme bereitstellen Bitte verteilen und assoziieren Sie entsprechend meinem Projekthintergrund, geben Sie mir [Marke] und [Slogan], versuchen Sie, so kurz wie möglich zu sein, leicht zu identifizieren, eingängig, nicht zungenbrecherisch, mit Erinnerungspunkten, Markenname nicht mehr als [5] Wörter, Slogan nicht mehr als [12] Wörter, geben Sie mir [12] Wörter. Der Markenname sollte nicht mehr als [5] Wörter und der Slogan nicht mehr als [12] Wörter umfassen, geben Sie mir [5] Optionen an.",
    "remark": "Erstellen Sie Ihr eigenes Branding-Programm mit Bezug auf die Namen und Slogans bekannter Marken. Beitrag von @b3ue."
  },
  "it": {
    "title": "Assistente per il brainstorming del marchio",
    "prompt": "For this task, we require two main parts:\n\n1. **Case Collection** - Utilize your vast training data and provide a selection of well-known brand names and slogans. The results should be evidence-based and be formatted in a visually appealing manner. The information will be used in the context of the project: [A Brief Background].\n\n2. **Proposal Generation** - Based on the project background, brainstorm and generate a series of proposals for new brand names and slogans. The brand names should be a maximum of 5 characters long, and the slogans should be a maximum of 12 characters long. Ensure that they are easy to recognize and remember, catchy, and not difficult to pronounce. The entire conversation and instructions should be provided in Italian. Please provide 5 proposals...",
    "description": "Questo promemoria è diviso in due sezioni (i parametri in [] possono essere liberamente modificati in base alle esigenze): 1. Raccolta di casi Ora ho bisogno che tu mi aiuti a fare brainstorming, rispondimi in [cinese] durante tutto il processo e presti attenzione all&#39;estetica del formato della risposta. In base allo sfondo del progetto [Breve descrizione], si prega di raccogliere il maggior numero possibile di casi basati su prove di nomi di marchi e slogan noti. 2. Fornire un piano, divergere e associare in base al background del mio progetto, fornire [marchio] e [slogan], cercare di essere brevi e facili da identificare, accattivanti, non goffi, avere punti di memoria e il nome del marchio non deve superare [5] parole, lo slogan non supera le [12] parole e forniscimi [5] soluzioni.",
    "remark": "Crea il tuo schema di branding facendo riferimento a nomi e slogan di marchi noti. Contributo di @b3ue."
  },
  "ru": {
    "title": "Ассистент мозгового штурма бренда",
    "prompt": "For this task, we require two main parts:\n\n1. **Case Collection** - Utilize your vast training data and provide a selection of well-known brand names and slogans. The results should be evidence-based and be formatted in a visually appealing manner. The information will be used in the context of the project: [A Brief Background].\n\n2. **Proposal Generation** - Based on the project background, brainstorm and generate a series of proposals for new brand names and slogans. The brand names should be a maximum of 5 characters long, and the slogans should be a maximum of 12 characters long. Ensure that they are easy to recognize and remember, catchy, and not difficult to pronounce. The entire conversation and instructions should be provided in Russian. Please provide 5 proposals...",
    "description": "Это напоминание разделено на два раздела (параметры в [] можно свободно изменять в соответствии с потребностями): 1. Сбор кейсов Теперь мне нужно, чтобы вы помогли мне провести мозговой штурм, ответили мне на [китайском] на протяжении всего процесса и обратили внимание на эстетику. формата ответа. Согласно предыстории проекта [Краткое описание], пожалуйста, соберите как можно больше доказательных кейсов известных торговых марок и слоганов. 2. Предоставьте план, пожалуйста, отклонитесь и свяжите в соответствии с моим проектным фоном, дайте [бренд] и [слоган], постарайтесь быть кратким и легко узнаваемым, броским, не неловким, иметь точки памяти, а название бренда не превышает [5] слов, лозунг не превышает [12] слов, и предоставить мне [5] решений.",
    "remark": "Создайте собственную схему брендинга, используя названия и слоганы известных брендов. Вклад от @b3ue."
  },
  "pt": {
    "title": "Assistente de brainstorm da marca",
    "prompt": "For this task, we require two main parts:\n\n1. **Case Collection** - Utilize your vast training data and provide a selection of well-known brand names and slogans. The results should be evidence-based and be formatted in a visually appealing manner. The information will be used in the context of the project: [A Brief Background].\n\n2. **Proposal Generation** - Based on the project background, brainstorm and generate a series of proposals for new brand names and slogans. The brand names should be a maximum of 5 characters long, and the slogans should be a maximum of 12 characters long. Ensure that they are easy to recognize and remember, catchy, and not difficult to pronounce. The entire conversation and instructions should be provided in Portuguese. Please provide 5 proposals...",
    "description": "Esta palavra de alerta é dividida em duas seções (os parâmetros em [] podem ser modificados livremente de acordo com as necessidades): 1. Coletando casos Agora preciso que você me ajude a fazer um brainstorming, responda-me em [chinês] durante todo o processo e preste atenção ao estética do formato de resposta. De acordo com o histórico do projeto [Breve descrição], colete o máximo possível de casos baseados em evidências de marcas e slogans conhecidos. 2. Para fornecer um plano, diverja e associe de acordo com o histórico do meu projeto, forneça [marca] e [slogan], tente ser curto e fácil de identificar, cativante, não estranho, tenha pontos de memória e o nome da marca não exceder [5] palavras, o slogan não exceder [12] palavras e fornecer-me [5] soluções.",
    "remark": "Crie seu próprio esquema de branding referindo-se aos nomes e slogans de marcas conhecidas. Contribuição de @b3ue."
  },
  "hi": {
    "title": "ब्रांड मंथन सहायक",
    "prompt": "For this task, we require two main parts:\n\n1. **Case Collection** - Utilize your vast training data and provide a selection of well-known brand names and slogans. The results should be evidence-based and be formatted in a visually appealing manner. The information will be used in the context of the project: [A Brief Background].\n\n2. **Proposal Generation** - Based on the project background, brainstorm and generate a series of proposals for new brand names and slogans. The brand names should be a maximum of 5 characters long, and the slogans should be a maximum of 12 characters long. Ensure that they are easy to recognize and remember, catchy, and not difficult to pronounce. The entire conversation and instructions should be provided in Hindi. Please provide 5 proposals...",
    "description": "इस अनुस्मारक को दो खंडों में विभाजित किया गया है ([] में मापदंडों को जरूरतों के अनुसार स्वतंत्र रूप से संशोधित किया जा सकता है): 1. मामलों को एकत्रित करना अब मुझे आपकी मदद की ज़रूरत है, विचार-मंथन करने में, पूरी प्रक्रिया के दौरान मुझे [चीनी] में उत्तर देने में, और सौंदर्यशास्त्र पर ध्यान देने में। उत्तर के प्रारूप का. परियोजना की पृष्ठभूमि [संक्षिप्त विवरण] के अनुसार, कृपया प्रसिद्ध ब्रांड नामों और नारों के यथासंभव साक्ष्य-आधारित मामले एकत्र करें। 2. एक योजना प्रदान करें, कृपया मेरे प्रोजेक्ट पृष्ठभूमि के अनुसार अलग-अलग और संबद्ध करें, [ब्रांड] और [नारा] दें, छोटा और पहचानने में आसान, आकर्षक, अजीब न हो, स्मृति बिंदु रखें, और ब्रांड नाम अधिक न हो [5] शब्द, नारा [12] शब्दों से अधिक नहीं है, और मुझे [5] समाधान प्रदान करें।",
    "remark": "प्रसिद्ध ब्रांडों के नाम और नारों का हवाला देकर अपनी खुद की ब्रांडिंग योजना बनाएं। @b3ue से योगदान."
  },
  "ar": {
    "title": "مساعد العصف الذهني للعلامة التجارية",
    "prompt": "For this task, we require two main parts:\n\n1. **Case Collection** - Utilize your vast training data and provide a selection of well-known brand names and slogans. The results should be evidence-based and be formatted in a visually appealing manner. The information will be used in the context of the project: [A Brief Background].\n\n2. **Proposal Generation** - Based on the project background, brainstorm and generate a series of proposals for new brand names and slogans. The brand names should be a maximum of 5 characters long, and the slogans should be a maximum of 12 characters long. Ensure that they are easy to recognize and remember, catchy, and not difficult to pronounce. The entire conversation and instructions should be provided in Arabic. Please provide 5 proposals...",
    "description": "تنقسم هذه الكلمة السريعة إلى قسمين (يمكن تعديل المعلمات في [] بحرية وفقًا للاحتياجات): 1. تجميع الحالات الآن أحتاج منك مساعدتي في تبادل الأفكار والإجابة بـ [الصينية] طوال العملية ، والاهتمام جماليات تنسيق الإجابة. وفقًا لخلفية المشروع [وصف موجز] ، يرجى جمع أكبر قدر ممكن من الحالات القائمة على الأدلة للأسماء التجارية والشعارات المعروفة. 2. لتقديم خطة ، يرجى التباعد والمشاركة وفقًا لخلفية مشروعي ، وإعطاء [العلامة التجارية] و [الشعار] ، وحاول أن تكون قصيرًا وسهل التحديد ، وجذابًا ، وليس محرجًا ، ولديك نقاط ذاكرة ، والاسم التجاري ليس كذلك يتجاوز [5] كلمات ، لا يتعدى الشعار [12] كلمة ، ويزودني بـ [5] حلول.",
    "remark": "قم بإنشاء مخطط العلامة التجارية الخاص بك من خلال الرجوع إلى أسماء وشعارات العلامات التجارية المعروفة. مساهمة من @ b3ue."
  },
  "bn": {
    "title": "ব্র্যান্ড ব্রেনস্টর্ম সহকারী",
    "prompt": "For this task, we require two main parts:\n\n1. **Case Collection** - Utilize your vast training data and provide a selection of well-known brand names and slogans. The results should be evidence-based and be formatted in a visually appealing manner. The information will be used in the context of the project: [A Brief Background].\n\n2. **Proposal Generation** - Based on the project background, brainstorm and generate a series of proposals for new brand names and slogans. The brand names should be a maximum of 5 characters long, and the slogans should be a maximum of 12 characters long. Ensure that they are easy to recognize and remember, catchy, and not difficult to pronounce. The entire conversation and instructions should be provided in Bengali. Please provide 5 proposals...",
    "description": "এই অনুস্মারকটিকে দুটি বিভাগে বিভক্ত করা হয়েছে (প্রয়োজন অনুসারে []-এ পরামিতিগুলি অবাধে পরিবর্তন করা যেতে পারে): 1. কেস সংগ্রহ করা এখন আমার আপনাকে সাহায্য করতে হবে আমাকে চিন্তাভাবনা করতে, পুরো প্রক্রিয়া জুড়ে [চীনা] ভাষায় উত্তর দিতে এবং নান্দনিকতার দিকে মনোযোগ দিতে হবে উত্তরের বিন্যাসের। প্রকল্পের পটভূমি অনুসারে [সংক্ষিপ্ত বিবরণ], অনুগ্রহ করে সুপরিচিত ব্র্যান্ডের নাম এবং স্লোগানের যতটা সম্ভব প্রমাণ-ভিত্তিক মামলা সংগ্রহ করুন। 2. একটি পরিকল্পনা প্রদান করুন, অনুগ্রহ করে আমার প্রজেক্ট ব্যাকগ্রাউন্ড অনুযায়ী বিচ্ছিন্ন করুন এবং যুক্ত করুন, [ব্র্যান্ড] এবং [স্লোগান] দিন, সংক্ষিপ্ত এবং সহজে সনাক্ত করার চেষ্টা করুন, আকর্ষণীয়, বিশ্রী নয়, মেমরি পয়েন্ট আছে এবং ব্র্যান্ডের নামটি অতিক্রম করবেন না [5] শব্দ, স্লোগানটি [12] শব্দের বেশি হয় না এবং আমাকে [5] সমাধান প্রদান করে।",
    "remark": "সুপরিচিত ব্র্যান্ডের নাম এবং স্লোগান উল্লেখ করে আপনার নিজস্ব ব্র্যান্ডিং স্কিম তৈরি করুন। @b3ue থেকে অবদান।"
  },
  "website": null,
  "tags": [
    "contribute",
    "company"
  ],
  "id": 254,
  "weight": 365
};

function PromptDetail() {
  return <PromptPage prompt={prompt} />;
}

export default PromptDetail;
