name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v7
        with:
          # 获取所有标记和分支的所有历史记录（updatetime 必须，否则每次都会变化）
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build

      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     # 这是文档部署到的分支名称
      #     branch: gh-pages
      #     folder: build

      # - name: 📂 Sync files
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      #   with:
      #     local-dir: build/
      #     server: ${{ secrets.ftp_host }}
      #     username: ${{ secrets.ftp_username }}
      #     password: ${{ secrets.ftp_password }}
      #     port: ${{ secrets.ftp_port }} # 建议更改默认的 21 端口
      #     timeout: 600000
